---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-operator
  namespace: sym-admin
spec:
  selector:
    matchLabels:
      name: mesh-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: mesh-operator
    spec:
      containers:
        - name: mesh-operator
          image: controller:latest
          imagePullPolicy: Always
          args:
            - "ctl"
            - "-v"
            - "4"
            - "max-concurrent-reconciles"
            - "1000"
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
