# permissions for end users to view serviceconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceconfig-viewer-role
rules:
- apiGroups:
  - mesh.symcn.com
  resources:
  - serviceconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mesh.symcn.com
  resources:
  - serviceconfigs/status
  verbs:
  - get
