apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: meshconfigs.mesh.symcn.com
spec:
  group: mesh.symcn.com
  names:
    kind: MeshConfig
    listKind: MeshConfigList
    plural: meshconfigs
    singular: meshconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: MeshConfig is the Schema for the meshconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MeshConfigSpec defines the desired state of MeshConfig
            properties:
              globalPolicy:
                description: Policy ...
                properties:
                  loadBalancer:
                    additionalProperties:
                      type: string
                    type: object
                  maxConnections:
                    format: int32
                    type: integer
                  maxRetries:
                    format: int32
                    type: integer
                  sourceLabels:
                    items:
                      description: SourceLabels ...
                      properties:
                        headers:
                          additionalProperties:
                            type: string
                          type: object
                        labels:
                          additionalProperties:
                            type: string
                          type: object
                        name:
                          type: string
                        route:
                          items:
                            description: Destination ...
                            properties:
                              subset:
                                type: string
                              weight:
                                format: int32
                                type: integer
                            type: object
                          type: array
                      type: object
                    type: array
                  timeout:
                    type: string
                type: object
              globalSubsets:
                items:
                  description: Subset ...
                  properties:
                    labels:
                      additionalProperties:
                        type: string
                      type: object
                    name:
                      type: string
                    policy:
                      description: Policy ...
                      properties:
                        loadBalancer:
                          additionalProperties:
                            type: string
                          type: object
                        maxConnections:
                          format: int32
                          type: integer
                        maxRetries:
                          format: int32
                          type: integer
                        sourceLabels:
                          items:
                            description: SourceLabels ...
                            properties:
                              headers:
                                additionalProperties:
                                  type: string
                                type: object
                              labels:
                                additionalProperties:
                                  type: string
                                type: object
                              name:
                                type: string
                              route:
                                items:
                                  description: Destination ...
                                  properties:
                                    subset:
                                      type: string
                                    weight:
                                      format: int32
                                      type: integer
                                  type: object
                                type: array
                            type: object
                          type: array
                        timeout:
                          type: string
                      type: object
                  required:
                  - labels
                  - name
                  type: object
                type: array
              matchHeaderLabelKeys:
                additionalProperties:
                  description: StringMatchType ...
                  type: string
                type: object
              matchSourceLabelKeys:
                items:
                  type: string
                type: array
              meshLabelsRemap:
                additionalProperties:
                  type: string
                type: object
              workloadEntryLabelKeys:
                items:
                  type: string
                type: array
            required:
            - globalPolicy
            - globalSubsets
            - matchHeaderLabelKeys
            - matchSourceLabelKeys
            - meshLabelsRemap
            - workloadEntryLabelKeys
            type: object
          status:
            description: MeshConfigStatus defines the observed state of MeshConfig
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
