apiVersion: mesh.symcn.com/v1
kind: AppMeshConfig
metadata:
  name: amc-order-api
spec:
  appName: order-api
  inject:                     
    logLevel: debug          
    sidecar: mosn           
  services:
    - name: com.test.order.service.OrderApiForAppClient
      ports:
        - name: dubbo-http
          protocol: HTTP
          number: 20882
      policy:
        loadBalancer:
          simple: ROUND_ROBIN
        maxConnections: 10
        timeout: 30ms
        maxRetries: 3
        route:
          - subset: blue
            weight: 20
          - subset: green
            weight: 80
      subsets:
        - name: blue
          labels:
            group: blue
          policy:
            timeout: 10ms
            maxRetries: 2
        - name: green
          labels:
            group: green
      instances:
        - host: 10.11.224.12
          zone: gz01
          group: blue
          labels:
            register: "true"
            dynamic: "true"
            weight: "50"
            release: "2.7.2-SNAPSHOT"
            sdkVersion: "2.7.2"
            side: "provider"
            timeout: "1000"
            retry: "3"
          port:
            name: dubbo-http
            protocol: HTTP
            number: 20882
        - host: 10.11.224.13
          zone: gz01
          group: blue
          labels:
            register: "true"
            dynamic: "true"
            weight: "50"
            release: "2.7.2-SNAPSHOT"
            sdkVersion: "2.7.2"
            side: "provider"
            timeout: "1000"
            retry: "3"
          port:
            name: dubbo-http
            protocol: HTTP
            number: 20882
        - host: 10.11.224.14
          zone: rz01
          group: green
          labels:
            register: "true"
            dynamic: "true"
            weight: "50"
            release: "2.7.2-SNAPSHOT"
            sdkVersion: "2.7.2"
            side: "provider"
            timeout: "1000"
            retry: "3"
          port:
            name: dubbo-http
            protocol: HTTP
            number: 20882
        - host: 10.11.224.15
          zone: rz02
          group: green
          labels:
            register: "true"
            dynamic: "true"
            weight: "50"
            release: "2.7.2-SNAPSHOT"
            sdkVersion: "2.7.2"
            side: "provider"
            timeout: "1000"
            retry: "3"
          port:
            name: dubbo-http
            protocol: HTTP
            number: 20882
        - host: 10.11.224.16
          zone: gz01
          group: gray
          labels:
          port:
            name: dubbo-http
            protocol: HTTP
            number: 20882
  policy:
    loadBalancer:
      simple: ROUND_ROBIN
    maxConnections: 100
    timeout: 5s
    maxRetries: 3
