apiVersion: mesh.symcn.com/v1
kind: AppMeshConfig
metadata:
  name: amc-order-api
  namespace: sym-admin
spec:
  appName: order-api
  inject:                     
    logLevel: debug          
    sidecar: mosn           
  services:
    - name: com.test.order.service.OrderApiForAppClient
      ports:
        - name: dubbo-http
          protocol: HTTP
          number: 20882
      policy:
        loadBalancer:
          simple: ROUND_ROBIN
        maxConnections: 10
        timeout: 30ms
        maxRetries: 3
        sourceLabels:
          - name: blue
            labels:
              sym-group: blue
            headers:
              sym-zone: gz01
            route:
              - subset: blue
                weight: 100
              - subset: green
                weight: 0
              - subset: gray
                weight: 0
          - name: green
            headers:
              sym-zone: gz01
              sym-lidc: gz01a
            labels:
              sym-group: green
            route:
              - subset: blue
                weight: 0
              - subset: green
                weight: 100
      subsets:
        - name: blue
          labels:
            sym-group: blue
          policy:
            timeout: 10ms
            maxRetries: 2
        - name: green
          labels:
            sym-group: green
      instances:
        - host: 10.11.224.11
          labels:
            zone: gz01
            flag: blue
            register: "true"
            dynamic: "true"
            weight: "50"
            release: "2.7.2-SNAPSHOT"
            sdkVersion: "2.7.2"
            side: "provider"
            timeout: "1000"
            retry: "3"
          port:
            name: dubbo-http
            protocol: HTTP
            number: 20882
        - host: 10.11.224.13
          labels:
            zone: gz01
            flag: green
            register: "true"
            dynamic: "true"
            weight: "50"
            release: "2.7.2-SNAPSHOT"
            sdkVersion: "2.7.2"
            side: "provider"
            timeout: "1000"
            retry: "3"
          port:
            name: dubbo-http
            protocol: HTTP
            number: 20882
        - host: 10.11.224.16
          labels:
            zone: gz01
            flag: gray
            register: "true"
            dynamic: "true"
            weight: "50"
            release: "2.7.2-SNAPSHOT"
            sdkVersion: "2.7.2"
            side: "provider"
          port:
            name: dubbo-http
            protocol: HTTP
            number: 20882
  policy:
    loadBalancer:
      simple: ROUND_ROBIN
    maxConnections: 100
    timeout: 5s
    maxRetries: 3
