apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appmeshconfigs.mesh.symcn.com
spec:
  group: mesh.symcn.com
  names:
    kind: AppMeshConfig
    listKind: AppMeshConfigList
    plural: appmeshconfigs
    singular: appmeshconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: AppMeshConfig is the Schema for the appmeshconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AppMeshConfigSpec ...
            properties:
              appName:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file'
                type: string
              inject:
                description: Inject ...
                properties:
                  logLevel:
                    type: string
                  sidecar:
                    type: string
                required:
                - sidecar
                type: object
              policy:
                description: Policy ...
                properties:
                  loadBalancer:
                    additionalProperties:
                      type: string
                    type: object
                  maxConnections:
                    format: int32
                    type: integer
                  maxRetries:
                    format: int32
                    type: integer
                  route:
                    items:
                      description: Destination ...
                      properties:
                        subset:
                          type: string
                        weight:
                          format: int32
                          type: integer
                      type: object
                    type: array
                  timeout:
                    type: string
                type: object
              services:
                items:
                  description: Service ...
                  properties:
                    instances:
                      items:
                        description: Instance ...
                        properties:
                          group:
                            type: string
                          host:
                            type: string
                          labels:
                            additionalProperties:
                              type: string
                            type: object
                          port:
                            description: Port ...
                            properties:
                              name:
                                type: string
                              number:
                                format: int32
                                type: integer
                              protocol:
                                type: string
                            required:
                            - name
                            - number
                            - protocol
                            type: object
                          weight:
                            format: int32
                            type: integer
                          zone:
                            type: string
                        required:
                        - group
                        - host
                        - port
                        - weight
                        - zone
                        type: object
                      type: array
                    name:
                      type: string
                    policy:
                      description: Policy ...
                      properties:
                        loadBalancer:
                          additionalProperties:
                            type: string
                          type: object
                        maxConnections:
                          format: int32
                          type: integer
                        maxRetries:
                          format: int32
                          type: integer
                        route:
                          items:
                            description: Destination ...
                            properties:
                              subset:
                                type: string
                              weight:
                                format: int32
                                type: integer
                            type: object
                          type: array
                        timeout:
                          type: string
                      type: object
                    ports:
                      items:
                        description: Port ...
                        properties:
                          name:
                            type: string
                          number:
                            format: int32
                            type: integer
                          protocol:
                            type: string
                        required:
                        - name
                        - number
                        - protocol
                        type: object
                      type: array
                    subsets:
                      items:
                        description: Subset ...
                        properties:
                          labels:
                            additionalProperties:
                              type: string
                            type: object
                          name:
                            type: string
                          policy:
                            description: Policy ...
                            properties:
                              loadBalancer:
                                additionalProperties:
                                  type: string
                                type: object
                              maxConnections:
                                format: int32
                                type: integer
                              maxRetries:
                                format: int32
                                type: integer
                              route:
                                items:
                                  description: Destination ...
                                  properties:
                                    subset:
                                      type: string
                                    weight:
                                      format: int32
                                      type: integer
                                  type: object
                                type: array
                              timeout:
                                type: string
                            type: object
                        required:
                        - labels
                        - name
                        type: object
                      type: array
                  type: object
                type: array
            required:
            - inject
            - policy
            - services
            type: object
          status:
            description: AppMeshConfigStatus defines the observed state of AppMeshConfig
            properties:
              lastUpdateTime:
                format: date-time
                type: string
              phase:
                description: ConfigPhase ...
                type: string
              status:
                description: Status ...
                properties:
                  destinationRule:
                    description: SubStatus ...
                    properties:
                      desired:
                        type: integer
                      distributed:
                        type: integer
                      undistributed:
                        type: integer
                    required:
                    - desired
                    - distributed
                    - undistributed
                    type: object
                  serviceEntry:
                    description: SubStatus ...
                    properties:
                      desired:
                        type: integer
                      distributed:
                        type: integer
                      undistributed:
                        type: integer
                    required:
                    - desired
                    - distributed
                    - undistributed
                    type: object
                  virtualService:
                    description: SubStatus ...
                    properties:
                      desired:
                        type: integer
                      distributed:
                        type: integer
                      undistributed:
                        type: integer
                    required:
                    - desired
                    - distributed
                    - undistributed
                    type: object
                  workloadEntry:
                    description: SubStatus ...
                    properties:
                      desired:
                        type: integer
                      distributed:
                        type: integer
                      undistributed:
                        type: integer
                    required:
                    - desired
                    - distributed
                    - undistributed
                    type: object
                required:
                - destinationRule
                - serviceEntry
                - virtualService
                - workloadEntry
                type: object
            required:
            - phase
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
