apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicemeshentries.mesh.symcn.com
spec:
  group: mesh.symcn.com
  names:
    kind: ServiceMeshEntry
    listKind: ServiceMeshEntryList
    plural: servicemeshentries
    singular: servicemeshentry
    shortNames:
      - sme
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
