apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-adapter
  namespace: sym-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mesh-adapter
  template:
    metadata:
      labels:
        name: mesh-adapter
    spec:
      serviceAccountName: mesh-operator
      containers:
        - name: mesh-adapter
          image: symcn.tencentcloudcr.com/symcn/mesh-operator:v0.0.2
          imagePullPolicy: Always
          args:
          - "adapter"
          - "--raddr"
          - "127.0.0.1:2181"
          - "--caddr"
          - "127.0.0.1:2181"
          - "-v"
          - "4"
          env:
            - name: OPERATOR_NAME
              value: "mesh-operator"
      hostAliases:
        - hostnames:
          - testhost.com
          ip: 10.10.10.10
