apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-operator
  namespace: sym-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mesh-operator
  template:
    metadata:
      labels:
        name: mesh-operator
    spec:
      serviceAccountName: mesh-operator
      containers:
        - name: mesh-operator
          image: symcn.tencentcloudcr.com/symcn/mesh-operator:v0.0.1
          imagePullPolicy: Always
          args:
          - "ctl"
          - "-v"
          - "4"
          env:
            - name: OPERATOR_NAME
              value: "mesh-operator"
