apiVersion: mesh.symcn.com/v1alpha1
kind: MeshConfig
metadata:
  name: sym-meshconfig
  namespace: sym-admin
spec:
  matchSourceLabelKeys:
    - sym-group
  workloadEntryLabelKeys:
    - sym-group
  meshLabelsRemap:
    flag: sym-group
  extractedLabels:
    - app
  sidecarSelectLabel: app
  sidecarDefaultHosts:
    - "istio-system/*"
    - "*/com.dmall.quasar.dsf.proxy.api.zoneproviderproxy"
    - "*/com.dmall.quasar.dsf.proxy.api.zoneconsumerproxy"
  globalSubsets:
    - name: blue
      labels:
        sym-group: blue
    - name: green
      labels:
        sym-group: green
    - name: gray
      isCanary: true
      labels:
        sym-group: gray
  globalPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    maxConnections: 100
    timeout: 5s
    maxRetries: 3
