apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceconfigs.mesh.symcn.com
spec:
  group: mesh.symcn.com
  names:
    kind: ServiceConfig
    listKind: ServiceConfigList
    plural: serviceconfigs
    singular: serviceconfig
    shortNames:
      - svcc
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
